### ISSUE TITLE
Playerctl shows nothing but an empty dot

### ISSUE THREAD

**Issue by M1ndo** [BlingCorp/bling#105]
I was trying to use playerctl module , however it does seem to work for some reason and it only shows a empty dot as notification.
in play_ctl.lua there's the following 
```lua
local naughty = require("naughty")
awesome.connect_signal("bling::playerctl::title_artist_album",
                       function(title, artist, art_path)
    naughty.notify({title = title, text = artist, image = art_path})
end)
```
And in rc.lua
```lua
local theme_path = string.format("%s/.config/awesome/themes/%s/theme.lua", os.getenv("HOME"), chosen_theme)
beautiful.init(theme_path)
local bling = require("lib.bling")
require("scripts.play_ctl")
... snip ...
awful.key({ altkey, }, "j", function () awesome.emit_signal("bling::playerctl::title_artist_album") end,
              {description = "Spot Pop Up", group = "Pop Ups"}),
```
Also Tried to use @Nooo37 bar.lua (Music Section) this [one](https://0x0.st/-vwo.lua) with 
```lua
awful.key({ modkey, }, "p", 
        function () 
            local last_notify = {}
            awesome.connect_signal("bling::playerctl::title_artist_album", function(title, artist, album)
            last_notify = naughty.notify {
                title=tostring(title),
                text=tostring(artist),
                icon = gears.surface.load_uncached_silently(album),
                timeout=2,
                replaces_id=last_notify.id,
            }
            end)
        end,
        {description = "PlayerCtl Pop Up", group = "Pop Ups"}),
```
however it didn't work at all i didn't show anything .
- Dot Screenshot
![Dot Screenshot](https://user-images.githubusercontent.com/44820142/131894371-299f2284-b90b-437a-8749-ddfeaba08d52.png)

**Comment by Nooo37** [comment]
I think you haven't enabled the signal with `bling.signal.playerctl.enable()`? At least I can't find that line in your config. https://blingcorp.github.io/bling/#/signals/pctl

**Comment by Nooo37** [comment]
Also mpris support (which is what playerctl uses to get title, album art etc) varies a lot between different players. For some you need dedicated plugins (for example iirc deadbeef, mpd), browsers usually have some sort of mpris support, the lollypop player has great mpris support etc.

**Comment by M1ndo** [comment]
> I think you haven't enabled the signal with `bling.signal.playerctl.enable()`? At least I can't find that line in your config. https://blingcorp.github.io/bling/#/signals/pctl

yes indeed , however it still show the same thing.
here's how i set it up 
```lua
local theme_path = string.format("%s/.config/awesome/themes/%s/theme.lua", os.getenv("HOME"), chosen_theme)
beautiful.init(theme_path)
local bling = require("lib.bling")
bling.signal.playerctl.enable()
require("scripts.play_ctl")
```
Using your config as mentioned above .
when using mod+p (multiple times)doesn't show anything , however when forwarding to another song (Spotify) it displays a notification (how many times called)
![image](https://user-images.githubusercontent.com/44820142/131898400-c501cf85-44ef-4fd3-a2ab-f12f6f9e2788.png)

**Comment by M1ndo** [comment]
> Also mpris support (which is what playerctl uses to get title, album art etc) varies a lot between different players. For some you need dedicated plugins (for example iirc deadbeef, mpd), browsers usually have some sort of mpris support, the lollypop player has great mpris support etc.

yes tho this shouldn't be the case for spotify .

**Comment by Nooo37** [comment]
Oh yeah, I should have looked at the snippets you provided before jumping into your config lol. So the last two snippets don't make much sense: `awesome.connect_signal("bling::playerctl::title_artist_album", function(param1, param2, ...)  .... end` means "run the given function everytime that the signal `bling::playerctl::title_artist_album` gets emitted (through `awesome.emit_signal("bling::playerctl::title_artist_album", param1, param2, ...)`)". All that bling does (from a user perspective) is to emit the singal with the right parameters so that your function can access the necessary info. 

- The first snippet makes sense: "Everytime that the title_artist_album signal gets fired, give me the notification"
- The second snippet: "Everytime I press 'j', run every function that connected to the title_arist_album signal (with all parameters as `nil` because none were given)" ???
- The third snippet: "Everytime I press 'p', connect the title_artist_album signal to the given function once more" ???

> yes tho this shouldn't be the case for spotify .

Ehhh. Spotify doesn't care that much. But it seems to work for you just fine considering the screenshot

**Comment by M1ndo** [comment]
Apparently i misunderstood the documentation, and the code i wrote made nonsense (which i finally understood it myself hours later lol),i thought this works like scratchpads . you assign a keybinding and it pops up shows you what u need and eventually timeout like your volume [pop up](https://github.com/Nooo37/dots/blob/master/awesome/popup_volume.lua) . this there any way i can get something like this to pop up 
![image](https://user-images.githubusercontent.com/44820142/131912534-345eb175-dfd3-4f25-98de-5398bd019460.png)

**Comment by Nooo37** [comment]
Sure there is a way. You create such a widget and then update the info on there based on the incomming signal. For my current widget that looks something like: 
```lua
awesome.connect_signal("bling::playerctl::title_artist_album", function(title, artist, album_path)
    mytextbox.markup = tostring(title) .. " - " .. tostring(artist)
    myimagebox:set_image(gears.surface.load_uncached_silently(album_path))
    myimagebox:emit_signal("widget::redraw_needed")
end)
```

And then you would also need to add a timeout similar to the one you saw in my volume pop up.

Doing all of that at once might be a little too much though. Since you don't seem to be familiar with signals yet I would advise you to get the following working before attempting the popup: Add a textbox to your wibar and make the textbox display the current song title by connecting to the bling signal. Everything else is really just an extension of that principle.

**Comment by M1ndo** [comment]
i finally got how playerctl signals work , i managed to create a pop up that displays title - artist like shown below , however couldn't fit progressbar.
meanwhile i got album_art to work after changing some stuff in playerctl_cli.lua , spotify artUrl is handled weirdly by default .
 Spotify mpris:artUrl looks like this ```https://open.spotify.com/image/song_id``` and downloading doesn't result to art cover file instead it just downloads a 403 page , in order to download the cover file u place this ```https://i.scdn.co/image/Song_id``` which will then download the cover.png .
To Fix this either by adding this 
```
link="$(playerctl metadata mpris:artUrl | cut -d/ -f5)"
curl -s "https://i.scdn.co/image/$link" --output $tmp_cover_path
```
or by adding this in your /etc/hosts file to redirect any requests from https://open.spotify.com/ to https://i.scdn.co 
```
151.101.38.248                open.spotify.com
```
- adding album art doesn't fit correctly and i have no idea how to fix it 
![image](https://user-images.githubusercontent.com/44820142/132024548-29c1d4fe-702e-44c2-bcfe-d21ea73db4ac.png)

- meanwhile just title - artist is how it supposed to be tho.
![image](https://user-images.githubusercontent.com/44820142/132025032-0693d9b1-d3a0-4d7d-9564-b18c3512e7a9.png)

Here's config [ctl_pop.lua](https://0x0.st/-vU0.lua)

**Comment by Nooo37** [comment]
> i finally understood how playerctl signals work

Then you also understood how every other signal in awesomewm works :partying_face:

> downloading doesn't result to art cover file instead it just downloads a 403 page

Yes, that's what I meant with "they don't care that much": https://community.spotify.com/t5/Desktop-Linux/MPRIS-cover-art-url-file-not-found/td-p/4920104

Anyway, I don't really want to teach widgeting in bling github issues. I don't think it's the right place nor do I think that the format performs that well with that task (feels like emailing to me). If you need that kind of quick, more general help, consider joining the unofficial awesomeWM discord server (just search on the subreddit for an invite link from a year ago) or the IRC I guess.
