### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by branwright1** [BlingCorp/bling#11]
### Show us your Awesome setup made with Bling and Love.

**Rules**
- Please use reactions instead of writting comments like "Nice setup!".
- Try posting images directly to github attaching them to comments.
- If you want to share your dotfiles post them along with image.
- **Please star Bling and follow Nooo37 and JavaCafe01 for their great work!**

**Comment by Nooo37** [comment]
Since people often don't use the possibility of changing the master counter, they forget about it but it is extremely usefull in the mstab layout (probably even more so than in other layouts). So here a quick reminder that it exists.

![](https://user-images.githubusercontent.com/70270606/101285449-7e3e9080-37e5-11eb-9776-3c2d737e9d9d.png)

**Comment by branwright1** [comment]
Tilled wallpaper module is pretty nice
![screeenshot](https://user-images.githubusercontent.com/71175207/101392749-055f3780-38be-11eb-8df9-a875a6981106.png)

**Comment by MCotocel** [comment]
https://user-images.githubusercontent.com/74227209/115113998-13287600-9f9e-11eb-88a0-30c422e76e4d.mov

Scratchpads with Awestore animations are useful and look great
