### ISSUE TITLE
Incorrect resolution when using tiled wallpaper module

### ISSUE THREAD

**Issue by MCotocel** [BlingCorp/bling#53]
When I login and start AwesomeWM, the tiled wallpaper appears like this:

<img width="2560" alt="Screenshot 2021-04-30 at 4 53 51 PM" src="https://user-images.githubusercontent.com/74227209/116697781-a7e69700-a9d4-11eb-8d74-daf531989749.png">

However, when reloading the config, the wallpaper correctly resizes to fill the whole screen.

I'm using Linux in a virtual machine, so that might be related.

**Comment by branwright1** [comment]
Are you using awesome from master branch? iif yes then it can be caused directly by WM or Xorg because doesn't handle HiDPI and high resolutions displays as it should. Just noticed that awesome-git doesn't load some parts of my config before reload (like tags for example when starts with 9 but after reload 3rd tag is selected and there is only 5 as it should be)

**Comment by MCotocel** [comment]
> Are you using awesome from master branch?

Yes, I'm using the master branch

> If yes then it can be caused directly by WM or Xorg because doesn't handle HiDPI and high resolutions displays as it should

So it's an issue with AwesomeWM or Xorg? If so, should I close this issue?

**Comment by branwright1** [comment]
> So it's an issue with AwesomeWM or Xorg? If so, should I close this issue?
I'm guessing both because Xorg uses 30+yo technologies and doesn't support modern ones (HDPI, high res, freesync and so on) and yeah same problems with tiled wallpaper and wallpaper in general (linux vm) on macbook.

**Comment by MCotocel** [comment]
Oh well. It's not a huge pain to reload the config on login, since I don't log out very often. Since it's not a problem with Bling, but with Xorg, I'll close this issue now.
