### ISSUE TITLE
Tabbed pick with dmenu doesn't work

### ISSUE THREAD

**Issue by Kasper24** [BlingCorp/bling#60]
I also tried passing in the dmenu arguement, but that didn't help - so that's not the issue

**Comment by Piterden** [comment]
Hello. Share your config please

**Comment by HeavyRain266** [comment]
> I also tried passing in the dmenu arguement, but that didn't help - so that's not the issue

Could you explain whole problem and how to reproduce it?

**Comment by Kasper24** [comment]
@Piterden @HeavyRain266 
All I do really is call bling.module.tabbed.pick_with_dmenu() or bling.module.tabbed.pick_with_dmenu(rofi -modi drun -show drun) - both didn't work

**Comment by Piterden** [comment]
It is important where did you call it from. And also important where exactly did you require it. 

(honestly I will never understand people asking for help with their broken code and not showing it)

**Comment by Kasper24** [comment]
> It is important where did you call it from. And also important where exactly did you require it.
> 
> (honestly I will never understand people asking for help with their broken code and not showing it)

I call it when I press a key, I thought this is self explanatory

`
awful.key    
{        
   modifiers = { alt },        
   key = "f",        
   group = "modules",        
   description = "pick client to add to tab group via dmenu",        
   on_press = function()            
      bling.module.tabbed.pick_with_dmenu(apps.rofi)        
   end,    
},
`

**Comment by Nooo37** [comment]
@Kasper24 It won't work if you call the function with `rofi -modi drun -show drun` as the argument because that command is for spawning applications and not for getting options to choose from from stdin which is what the module depends on (you would have to use something like `rofi -dmenu -i`). 

But you also said it didn't work without the passed argument right? Maybe try calling it from the command line with `awesome-client 'require("bling").module.tabbed.pick_with_dmenu()'` and tell us if that worked or not. (also make sure to have rofi installed obviously)

**Comment by Nooo37** [comment]
So a discussion on the discord server crystalized the following issues:
- not being able to use pick_with_dmenu on already tabbed clients
-  when using pick_with_dmenu the client gets tabbed before finishing the action of selecting one client
- tabbar not updating directly after calling the pop function and thus removing one client from the tabbing group
- not all clients show up in the dmenu picker when there are a lot of clients open (for example like 10 terminals)
